<!DOCTYPE html>
<html lang="en-US">
	<head>
		<title>Web Application</title>
		<meta http-equiv="X-UA-Compatible" content="chrome=1;IE=edge">
		<meta http-equiv="Content-type" content="text/html; charset=utf-8">
		<link rel="stylesheet" href="/styles/production.min.css" type="text/css" media="screen" charset="utf-8">
		<link href="/" rel="home">
	</head>

	<body>
		<?php echo $_YIELD_; ?>
	</body>
</html>
